# Generated by Django 2.2.17 on 2021-06-06 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210519_0415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicerole',
            name='policies',
        ),
        migrations.DeleteModel(
            name='DevicePolicies',
        ),
        migrations.DeleteModel(
            name='DeviceRole',
        ),
    ]
