# Generated by Django 2.2.17 on 2021-06-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210606_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceinterface',
            name='description',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
